var phantomsgeojson = {"type": "FeatureCollection",                                                                             "features": [



{ "type": "Feature", "properties": { "FID": 1577565, "NAME": "Cutter", "CLASS": "Populated Place", "CTY": "Douglas", "TOWN" : null, "PHOTO1": "cutter_locale.jpg", "PHOTO2": null, "PHOTO3": null, "PHOTO4": null, "LAT": 46.6329954, "LONG": -91.9588007, "MAP": "Parkland", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "There are no residential buildings in this area. There are a few farms to the east of the railroad.", "ON_TOPO22": "Y", "GOOD_EX": "Y" }, "geometry": { "type": "Point", "coordinates": [ -91.9588007, 46.6329954 ] } },



{ "type": "Feature", "properties": { "FID": 1573741, "NAME": "Sauntry", "CLASS": "Populated Place", "CTY": "Douglas", "TOWN" : null, "PHOTO1": "sauntry_locale.jpg", "PHOTO2": null, "PHOTO3": null, "PHOTO4": null, "LAT": 46.3743854, "LONG": -91.8226892, "MAP": "Solon Springs", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "This location contains one improved residential parcel and also a church. There is no community here, although theer is a cluster of buildings to the east along US-53.", "ON_TOPO22": "Y", "GOOD_EX": null }, "geometry": { "type": "Point", "coordinates": [ -91.8225, 46.3744 ] } },



{ "type": "Feature", "properties": { "FID": 0, "NAME": "Butts Corners", "CLASS": "", "CTY": "", "TOWN": "", "PHOTO1": "butts_corners_locale.jpg", "PHOTO2": "butts_corners_road.jpg", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community here. One farm on NW corner.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.333419, 42.81678 ] } },


{ "type": "Feature", "properties": { "FID": 1577799, "NAME": "Ross Crossing", "CLASS": "Populated Place", "CTY": "Green", "TOWN" : null, "PHOTO1": "ross_crossing_locale.jpg", "PHOTO2": null, "PHOTO3": null, "PHOTO4": null, "LAT": 42.8291695, "LONG": -89.5523432, "MAP": "Belleville", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "No community here, 2022", "ON_TOPO22": "NO", "GOOD_EX": null }, "geometry": { "type": "Point", "coordinates": [ -89.5523432, 42.8291695, 1577799.0 ] } },




{ "type": "Feature", "properties": { "FID": 1577836, "NAME": "Stearns", "CLASS": "Populated Place", "CTY": "Green", "TOWN" : null, "PHOTO1": null, "PHOTO2": null, "PHOTO3": null, "PHOTO4": null, "LAT": 42.6563961, "LONG": -89.6073424, "MAP": "Monticello", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "No community here. One farm in area.", "ON_TOPO22": "Y", "GOOD_EX": "Y" }, "geometry": { "type": "Point", "coordinates": [ -89.6073424, 42.6563961, 1577836.0 ] } },




{ "type": "Feature", "properties": { "FID": 1577816, "NAME": "Schultz", "CLASS": "Populated Place", "CTY": "Green", "TOWN" : null, "PHOTO1": null, "PHOTO2": null, "PHOTO3": null, "PHOTO4": null, "LAT": 42.6900064, "LONG": -89.6026205, "MAP": "Monticello", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "There are some single-family homes here, but no signage was found.", "ON_TOPO22": "Y", "GOOD_EX": "Y" }, "geometry": { "type": "Point", "coordinates": [ -89.6026205, 42.6900064, 1577816.0 ] } },










{ "type": "Feature", "properties": { "FID": 0, "NAME": "Buss's Corners", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "busss_corners_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community here.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.207716, 43.16596 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Bakers Corners", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "bakers_corners_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community here.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.18693, 43.26816 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Aldens Corners", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "aldens_corners.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community here.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.64043, 43.22029 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Five Points", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "five_points_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community here. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.53337, 43.01676 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Adsit", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "adsit_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Shown on 1896 Sun Prairie USGS topo map.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.1057139, 43.07829 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Door Creek", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "door_creek_locale.jpg", "PHOTO2": "door_creek_east.jpg", "PHOTO3": "door_creek_cemetery.jpg", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Shown on 1896 Sun Prairie USGS topo map. Also in GNIS and on 2018 USGS US Topo map. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.200036, 43.03224] } },



{ "type": "Feature", "properties": { "FID": 1567790, "NAME": "Lakeview", "CLASS": "Populated Place", "CTY": "Dane", "TOWN" : null, "PHOTO1": "lakeview_locale.jpg", "PHOTO2": "lake_view_plaque.jpg", "PHOTO3": null, "PHOTO4": null, "LAT": 42.9752768, "LONG": -89.3720634, "MAP": "Rutland", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "N", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "Shown on 1894 Evansville USGS topo map.", "ON_TOPO22": "Y", "GOOD_EX": null }, "geometry": { "type": "Point", "coordinates": [ -89.3720634, 42.9752768, 1567790.0 ] } },





{ "type": "Feature", "properties": { "FID": 0, "NAME": "Marshall Station", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "marshall_station_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Shown on historic USGS topo maps." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.05935, 43.1780 ] } },



{ "type": "Feature", "properties": { "FID": 1570632, "NAME": "Oak Hall", "CLASS": "Populated Place", "CTY": "Dane", "TOWN" : null, "PHOTO1": "oak_hall_locale.jpg", "PHOTO2": null, "PHOTO3": null, "PHOTO4": null, "LAT": 42.950555, "LONG": -89.4370645, "MAP": "Oregon", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "N", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "on historic USGS topo maps.", "ON_TOPO22": "Y", "GOOD_EX": null }, "geometry": { "type": "Point", "coordinates": [ -89.4370645, 42.950555, 1570632.0 ] } },


{ "type": "Feature", "properties": { "FID": 0, "NAME": "Stone", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "stone_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Shown on historic USGS topo maps. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.3105, 42.875161 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Story (Storytown)", "CLASS": "", "CTY": "Dane", "TOWN": "", "PHOTO1": "storytown_plaque.jpg", "PHOTO2": "story_locale.jpg", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Shown on historic USGS topo maps.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.473, 42.9002] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Fox Creek", "CLASS": "", "CTY": "Polk", "TOWN": "Georgetown town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community or signs found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.345471, 45.483567 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Jewett", "CLASS": "", "CTY": "St. Croix", "TOWN": "Erin Prairie town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y/N", "IN_GNIS": "Y", "IN_FOCHS": "Y", "NOTES": "No community or signs found. On google.", "ON_TOPO22": "Y", "GOOD_EX": "YY"}, "geometry": { "type": "Point", "coordinates": [ -92.436305, 45.117465 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Salmo", "CLASS": "", "CTY": "Bayfield", "TOWN": "Bayfield town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community or signs found. On google." ,"ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.865184, 46.781323 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Sand Bay", "CLASS": "", "CTY": "Bayfield", "TOWN": "Russell town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "A National Seashore facility, not a community.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.891022, 46.945763 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Washington", "CLASS": "", "CTY": "Door", "TOWN": "Washington town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No distinct community at this location. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -86.931508, 45.394703 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Detroit Harbor", "CLASS": "", "CTY": "Door", "TOWN": "Washington town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No distinct community at this location. Main business district on island is about a mile north of this location.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -86.930673, 45.35665 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Norton", "CLASS": "", "CTY": "Dunn", "TOWN": "Tainter town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.834341, 45.01635 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Dewey", "CLASS": "", "CTY": "Douglas", "TOWN": "Superior town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.244916, 46.569385 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Coomer", "CLASS": "", "CTY": "Burnett", "TOWN": "La Follette town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.257134, 45.747447 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Bashaw", "CLASS": "", "CTY": "Burnett", "TOWN": "Dewey town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.063237, 45.769113 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Chittamo", "CLASS": "", "CTY": "Washburn", "TOWN": "Frog Creek town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "Y", "NOTES": "Not found. On google.", "ON_TOPO22": "Y", "GOOD_EX": "Y"}, "geometry": { "type": "Point", "coordinates": [ -91.716572, 46.127999 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Winneboujou", "CLASS": "", "CTY": "Douglas", "TOWN": "Brule town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.60027961, 46.51704125 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Bellwood", "CLASS": "", "CTY": "Douglas", "TOWN": "Brule town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found/historical. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.637688, 46.571884 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Blueberry", "CLASS": "", "CTY": "Douglas", "TOWN": "Maple town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found/historical. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.668799, 46.580217 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Joel", "CLASS": "", "CTY": "Polk", "TOWN": "Clayton town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.234632, 45.360515 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Johannesburg", "CLASS": "", "CTY": "St. Croix", "TOWN": "Star Prairie town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.594089, 45.165243 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Yarnell", "CLASS": "", "CTY": "Sawyer", "TOWN": "Couderay town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community or signs found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.419329, 45.726901 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Bear Lake", "CLASS": "", "CTY": "Rusk", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community or signs found." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.47909756, 45.31314613 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Shanagolden", "CLASS": "", "CTY": "Ashland", "TOWN": "Shanagolden town", "PHOTO1": "shanagolden.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Historical. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.62665672, 46.12037874 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Lennox", "CLASS": "", "CTY": "Oneida", "TOWN": "Schoepke town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.071783, 45.511905 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Nashville", "CLASS": "", "CTY": "Forest", "TOWN": "Nashville town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.024838, 45.522739 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Glendale", "CLASS": "", "CTY": "Monroe", "TOWN": "Glendale town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "Kendall East", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "Y", "NOTES": "Community not found. On google." , "ON_TOPO22": "Y", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.345685, 43.782192 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Mount Tabor", "CLASS": "", "CTY": "Vernon", "TOWN": "Forest town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.454296, 43.700527 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Ridgeville", "CLASS": "", "CTY": "Monroe", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.56174235, 43.88537592 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Tamarack", "CLASS": "", "CTY": "Trempealeau", "TOWN": "Arcadia town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.447929, 44.174962 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Czechville", "CLASS": "", "CTY": "Buffalo", "TOWN": "Milton town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.773487, 44.187186 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Disco", "CLASS": "", "CTY": "Jackson", "TOWN": "Albion town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.009034, 44.262182 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Mosling", "CLASS": "", "CTY": "Oconto", "TOWN": "Underhill town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.369546, 44.868879 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Purdy", "CLASS": "", "CTY": "Vernon", "TOWN": "Sterling town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found, April 2019. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.048185, 43.516917 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Horseman", "CLASS": "", "CTY": "Barron", "TOWN": "Doyle town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found, Oct 2019. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.559608, 45.494404 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Keene", "CLASS": "", "CTY": "Portage", "TOWN": "Buena Vista town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.474284, 44.366915 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Oakland", "CLASS": "", "CTY": "Jefferson", "TOWN": "Oakland town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.955664, 42.976669 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Phipps", "CLASS": "", "CTY": "Sawyer", "TOWN": "Lenroot town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.413511, 46.062729 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Saylesville", "CLASS": "", "CTY": "Waukesha", "TOWN": "Genesee town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.320372, 42.949456 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Vaudreuil", "CLASS": "", "CTY": "Jackson", "TOWN": "Brockway town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.809863, 44.30635 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Gagen", "CLASS": "", "CTY": "Oneida", "TOWN": "Piehl town", "PHOTO1": "gagen_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Road sign, but no community. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.138178, 45.662458 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Dudley", "CLASS": "", "CTY": "Lincoln", "TOWN": "Russell town", "PHOTO1": "dudley_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "Gleason", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "Y", "NOTES": "Road sign, but no community. On google." , "ON_TOPO22": "Y", "GOOD_EX": "YY"}, "geometry": { "type": "Point", "coordinates": [ -89.46644748, 45.33540533 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Orion", "CLASS": "", "CTY": "Richland", "TOWN": "Orion town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.427902, 43.203042 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Westport", "CLASS": "", "CTY": "Richland", "TOWN": "Richwood town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.641237, 43.204983 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Plugtown", "CLASS": "", "CTY": "Crawford", "TOWN": "Scott town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.74846, 43.222481 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Dover", "CLASS": "", "CTY": " ", "TOWN": " ", "PHOTO1": "dover_plaque.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Historic village. Not in original uninc place list." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.8387, 43.1625 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Ash Ridge", "CLASS": "", "CTY": "Richland", "TOWN": " ", "PHOTO1": "ash_ridge_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Ash Ridge Drive street sign only signage found. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.54956778, 43.47370703 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Kickapoo Center", "CLASS": "", "CTY": "Vernon", "TOWN": " ", "PHOTO1": "kickapoo_center_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "Sugar Grove", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "N", "IN_FOCHS": "Y", "NOTES": "Kickapoo Center Lane sign is only signage found. No community here, just a few isolated houses. On google." , "ON_TOPO22": "N", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.69828439, 43.47176395 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Middle River", "CLASS": "", "CTY": "Douglas", "TOWN": " ", "PHOTO1": "middle_river_health_center.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community, just isolated houses. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.89639473, 46.56484899 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Requa", "CLASS": "", "CTY": "Jackson", "TOWN": "Garfield town", "PHOTO1": "requa_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Requa Road sign is the only signage found. No community, just isplated houses. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.144877, 44.586628 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Ross", "CLASS": "", "CTY": "Vernon", "TOWN": "Liberty town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. on google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.753186, 43.541085 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Hines", "CLASS": "", "CTY": "Douglas", "TOWN": "Hawthorne town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "A RR crossing. No community. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.90961557, 46.54321015 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Beaver Brook", "CLASS": "", "CTY": "Washburn", "TOWN": "Beaver Brook town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No signs or community visible from Hwy 53. On google.",  "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.839062, 45.753282 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Metomen", "CLASS": "", "CTY": "Fond du Lac", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.80537982, 43.78446638 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Green Lake Station", "CLASS": "", "CTY": "Green Lake", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not to be confused with Green Lake. No sign seen south of Hwy 23-49 or east of Cty A." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.94781495, 43.85697549 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "East Friesland", "CLASS": "", "CTY": "Columbia", "TOWN": "Randolph town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not to be confused with Friesland village. No evidence of East Friesland found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.047056, 43.600817 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "South Randolph", "CLASS": "", "CTY": "Dodge", "TOWN": "Westford town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.998999, 43.511097 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Bowers", "CLASS": "", "CTY": "Walworth", "TOWN": "Lafayette town", "PHOTO1": "bowers_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Only sign found is for Bowers Road. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.46270212, 42.68651901 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Granite Heights", "CLASS": "", "CTY": "Marathon", "TOWN": "Texas town", "PHOTO1": "granite_heights_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "Brokaw", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "Y", "NOTES": "Found only a Granite Heights Road address sign. On google.", "ON_TOPO22": "Y", "GOOD_EX": "YY"}, "geometry": { "type": "Point", "coordinates": [ -89.64038094, 45.06023831 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Norway Grove", "CLASS": "", "CTY": "Dane", "TOWN": "Vienna town", "PHOTO1": "norway_grove_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Found only a Norway Grove Road sign. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.402617, 43.248602 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Nye", "CLASS": "", "CTY": "Polk", "TOWN": "Osceola town", "PHOTO1": "nye_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Found only a Nye Lane sign. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.580479, 45.314407 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Helena", "CLASS": "", "CTY": "Iowa", "TOWN": "Arena town", "PHOTO1": "helena_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Found only a Helena Road sign.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.022346, 43.171381 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Seymour Corners", "CLASS": "", "CTY": "Lafayette", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.24988096, 42.66773081 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Exeter", "CLASS": "", "CTY": "Green", "TOWN": "Exeter town", "PHOTO1": "exeter_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.583176, 42.790559 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Sherwood", "CLASS": "", "CTY": "Clark", "TOWN": "Sherwood town", "PHOTO1": "sherwood_cemetery.jpg", "PHOTO2": "sherwood_locale.jpg", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Found only a Sherwood Town Cemetery. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.355689, 44.467462 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Cutler", "CLASS": "", "CTY": "Juneau", "TOWN": "Cutler town", "PHOTO1": "cutler_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Found only a street sign. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.236797, 44.025798 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Meadow Valley", "CLASS": "", "CTY": "Juneau", "TOWN": "Kingston town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found, Aug 2016.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.221244, 44.215241 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Norway Ridge", "CLASS": "", "CTY": "Monroe", "TOWN": "Scott town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found, Aug 2016. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.329298, 44.124686 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Kirby", "CLASS": "", "CTY": "Monroe", "TOWN": "Lincoln town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found, Aug 2016. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.539299, 44.090519 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Barksdale", "CLASS": "", "CTY": "Bayfield", "TOWN": "Barksdale town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No signs on WI-13. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.932131, 46.62133 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Harrison", "CLASS": "", "CTY": "Calumet", "TOWN": "Harrison town", "PHOTO1": "harrison_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Found only Harrison Road sign. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.291772, 44.134155 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Leslie", "CLASS": "", "CTY": "Lafayette", "TOWN": "Belmont town", "PHOTO1": "leslie_plaque.jpg", "PHOTO2": "leslie_buildings.jpg", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Location of the original territorial capital in Belmont. No community here, just one inhabited house and two historical buildings. No signs for Leslie found, Sept 2017. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.36647899, 42.77099417 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Bradley", "CLASS": "", "CTY": "Marathon", "TOWN": "Cleveland town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Sept 2017. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.01538302, 44.80098082 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Little Rose", "CLASS": "", "CTY": "Marathon", "TOWN": "Eau Pleine town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Sept 2017. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.17094202, 44.80070282 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Little Black", "CLASS": "", "CTY": "Taylor", "TOWN": "Little Black town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Sept 2017. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.329583, 45.106079 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Penokee Gap (Penokee)", "CLASS": "", "CTY": "Ashland", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Sept 2017. Penokee on google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.69664864, 46.31369899 ] } },




{ "type": "Feature", "properties": { "FID": 0, "NAME": "Clifford", "CLASS": "", "CTY": "Lincoln", "TOWN": "Lynne town", "PHOTO1": "clifford_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "Y", "NOTES": "Able to find only a Clifford Road sign. No community found. On google.", "ON_TOPO22": "Y", "GOOD_EX": "YYY"}, "geometry": { "type": "Point", "coordinates": [ -90.04424948, 45.55512833 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "McCord", "CLASS": "", "CTY": "Lincoln", "TOWN": "Little Rice town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Found McCord Rd sign, but no community. On google.",  "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.90063548, 45.55513033 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Buck Creek", "CLASS": "", "CTY": "Richland", "TOWN": "Rockbridge town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.361515, 43.420536 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Potts Corners", "CLASS": "", "CTY": "Vernon", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.64767695, 43.63193855 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Dilly", "CLASS": "", "CTY": "Vernon", "TOWN": "Forest town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.440129, 43.642195 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Greenwood", "CLASS": "", "CTY": "Vernon", "TOWN": "Greenwood town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.418462, 43.563864 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Troy", "CLASS": "", "CTY": "Walworth", "TOWN": "Troy town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Nov. 2017. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.46298012, 42.77401801 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Vienna", "CLASS": "", "CTY": "Walworth", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Sept. 2017.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.33141478, 42.71284187 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Tyrone", "CLASS": "", "CTY": "Green", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Dec. 2017. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.40143723, 42.50073145 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Clay", "CLASS": "", "CTY": "Jackson", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Jan 2018.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.68041073, 44.39599794 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Tioga", "CLASS": "", "CTY": "Clark", "TOWN": "Hendren town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "Rock Dam Lake", "CREATED": "", "EDITED": "", "ON_GOOGLE": "N", "IN_GNIS": "Y", "IN_FOCHS": "YY", "NOTES": "No community found, Jan 2018.", "ON_TOPO22": "", "GOOD_EX": "YYYY"}, "geometry": { "type": "Point", "coordinates": [ -90.793201, 44.684128 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Globe", "CLASS": "", "CTY": "Clark", "TOWN": "Weston town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "Willard", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "Y", "NOTES": "No community found, Jan 2018. On google.", "ON_TOPO22": "Y", "GOOD_EX": "YYY"}, "geometry": { "type": "Point", "coordinates": [ -90.659308, 44.654406 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Sidney", "CLASS": "", "CTY": "Clark", "TOWN": "Pine Valley town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Jan 2018. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.638751, 44.552739 ] } },

{ "type": "Feature", "properties": { "FID": 1578606, "NAME": "Neptune", "CLASS": "Populated Place", "CTY": "Richland", "TOWN" : "Ithaca town", "PHOTO1": null, "PHOTO2": null, "PHOTO3": null, "PHOTO4": null, "LAT": 43.3730389, "LONG": -90.2673479, "MAP": "Sextonville", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "No community found, Jan 2018. On google.", "ON_TOPO22": "Y", "GOOD_EX": null }, "geometry": { "type": "Point", "coordinates": [ -90.2673479, 43.3730389, 1578606.0 ] } },


{ "type": "Feature", "properties": { "FID": 0, "NAME": "Union Church", "CLASS": "", "CTY": "Racine", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Jan 2018. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.069253, 42.843627 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Kneeland", "CLASS": "", "CTY": "Racine", "TOWN": "Raymond town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Jan 2018. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.008417, 42.826683 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Edwards", "CLASS": "", "CTY": "Sheboygan", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, March 2018.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -87.83079985, 43.89136657 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Hamburg", "CLASS": "", "CTY": "Marathon", "TOWN": "Hamburg town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Only a single church. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.88594394, 45.09079331 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Brushville", "CLASS": "", "CTY": "", "TOWN": "", "PHOTO1": "brushville_cemetery.jpg", "PHOTO2": "brushville_school.jpg", "PHOTO3": "brushville_school_plaque.jpg", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not in original uninc place list. No community present. Historical? On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.9871, 44.1701 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Russell", "CLASS": "", "CTY": "Trempealeau", "TOWN": "Chimney Rock town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, May 2018. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.478489, 44.42802 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Tarrant", "CLASS": "", "CTY": "Pepin", "TOWN": "Lima town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, May 2018. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.84322, 44.596631 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Darbellay", "CLASS": "", "CTY": "Door", "TOWN": "", "PHOTO1": "darbellay_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. Not in original uninc place list", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -87.7237026, 44.6176802 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Sandy Bay", "CLASS": "", "CTY": " ", "TOWN": " ", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Not in original uninc place list. No community, Oct 2018.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -87.5427513, 44.3508694 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Clyde", "CLASS": "", "CTY": " ", "TOWN": " ", "PHOTO1": "clyde_hill_road.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -87.5823782, 44.5165737 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Ulao", "CLASS": "", "CTY": "Ozaukee", "TOWN": "Grafton village", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. Locale is a freeway exit with a gas station and a few other businesses, but no community, Nov 2018.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -87.916477, 43.32056 ] } },


{ "type": "Feature", "properties": { "FID": 1577675, "NAME": "Keowns", "CLASS": "Populated Place", "CTY": "Washington", "TOWN" : "Trenton town", "PHOTO1": null, "PHOTO2": null, "PHOTO3": null, "PHOTO4": null, "LAT": 43.3686129, "LONG": -88.1362042, "MAP": "Jackson", "CREATED": "8\/29\/1980", "EDITED": null, "ON_GOOGLE": "N/Y", "IN_GNIS": "Y", "IN_FOCHS": "N", "NOTES": "No community found, Nov 2018. On google.", "ON_TOPO22": "Y", "GOOD_EX": "Y" }, "geometry": { "type": "Point", "coordinates": [ -88.1362042, 43.3686129, 1577675.0 ] } },



{ "type": "Feature", "properties": { "FID": 0, "NAME": "Hurricane", "CLASS": "", "CTY": "Grant", "TOWN": "South Lancaster town", "PHOTO1": "hurricane_locale.jpg", "PHOTO2": "hurricane_cemetery.jpg", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Only a single building remains at this crossroads, April 2019. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.771237, 42.784713 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Romance", "CLASS": "", "CTY": "Vernon", "TOWN": "Harmony town", "PHOTO1": "romance_business.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Community not found, April 2019. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.144853, 43.552194 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Woodstock", "CLASS": "", "CTY": "Richland", "TOWN": "Henrietta town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "Gillingham", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "Y", "IN_FOCHS": "Y", "NOTES": "Community not found, April 2019. On google.", "ON_TOPO22": "Y", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.42735, 43.472477 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Exile", "CLASS": "", "CTY": "Pierce", "TOWN": "Rock Elm town", "PHOTO1": "exile_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, May 2019. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.165734, 44.699132 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Red Cedar", "CLASS": "", "CTY": "", "TOWN": "", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, May 2019. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -91.8844, 44.6886 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Harshaw", "CLASS": "", "CTY": "Oneida", "TOWN": "Cassian town", "PHOTO1": "old_harshaw_plaque.jpg", "PHOTO2": "harshaw_locale.jpg", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.655418, 45.665513 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Goodnow", "CLASS": "", "CTY": "Oneida", "TOWN": "Cassian town", "PHOTO1": "goodnow_plaque.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -89.671808, 45.697179 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Riverside", "CLASS": "", "CTY": "Burnett", "TOWN": "Blaine town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Jan 2020. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.247693, 46.076331 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Chaffey", "CLASS": "", "CTY": "Douglas", "TOWN": "Summit town", "PHOTO1": "", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "No community found, Jan 2020. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -92.16459676, 46.39772672 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Clyman Junction", "CLASS": "", "CTY": "Dodge", "TOWN": "Clyman town", "PHOTO1": "clyman_junction_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Clyman is on google." , "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -88.717881, 43.325273 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Orange Mill", "CLASS": "", "CTY": "Juneau", "TOWN": "Orange town", "PHOTO1": "orange_mill_building.jpg", "PHOTO2": "orange_mill_school.jpg", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "Historical locale with old mill and school. No signs found. On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.232352, 43.901634 ] } },

{ "type": "Feature", "properties": { "FID": 0, "NAME": "Atwood", "CLASS": "", "CTY": "Clark", "TOWN": "Green Grove town", "PHOTO1": "atwood_locale.jpg", "PHOTO2": "", "PHOTO3": "", "PHOTO4": "", "LAT": 0.0, "LONG": 0.0, "MAP": "", "CREATED": "", "EDITED": "", "ON_GOOGLE": "Y", "IN_GNIS": "", "IN_FOCHS": "", "NOTES": "On google.", "ON_TOPO22": "", "GOOD_EX": ""}, "geometry": { "type": "Point", "coordinates": [ -90.481803, 44.886078 ] } }

]
};
